language: c

compiler:
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libssl-dev yasm libgmp-dev libpcap-dev pkg-config debhelper libnet1-dev
  - sudo apt-get install fglrx-dev opencl-headers || true
  - export OMP_NUM_THREADS=4
script:
  - ./configure && make & make install
  - ./hello
